captureDirectory: captures
completeDirectory: complete
modelScanInterval: 120      # Co ile sekund pełny rescan online modeli (uzupełnienie eventów)
debug: true
minFileSizeMb: 5
maxConcurrentRecordings: 50 # Limit jednoczesnych nagrań
